### PR TITLE
Bump kubernetes version to 1.19.7

### PR DESCRIPTION
**Pull request by ingvagabund**
https://github.com/kubernetes/kubernetes/releases/tag/v1.19.7

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/approve
/lgtm

**Comment by damemi** [comment]
/hold
why 2 PRs @ingvagabund ? https://github.com/kubernetes-sigs/cluster-capacity/pull/134

**Comment by ingvagabund** [comment]
One PR for each rebase for better tracking

**Comment by damemi** [comment]
> One PR for each rebase for better tracking

sgtm

**Pull request merged**
