### PR TITLE
1.24 k8s bump

### PR DESCRIPTION
**Pull request by knelasevero**
1.24 k8s bump

CI in https://github.com/kubernetes/test-infra/pull/27596

### CODE REVIEW

**Comment by ingvagabund** [comment]
@knelasevero https://github.com/kubernetes-sigs/cluster-capacity/blob/master/test/run-e2e-tests.sh#L21 needs to be updated to newer version as well. E.g. https://github.com/kubernetes-sigs/descheduler/blob/master/test/run-e2e-tests.sh#L30

**Comment by knelasevero** [comment]
@ingvagabund is something else needed  here?

**Pull request merged**
